### ISSUE TITLE
Can't install this deepgram node

### ISSUE THREAD

**Issue by gab-luz** [Walid-Azur/n8n-nodes-deepgram#1]
I got this message when trying to install your node:
 Error loading package "n8n-nodes-deepgram" :Package could not be installed - check logs for details 

I've tried to install it manually using npm inside container but I got this error:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/mestre/.asdf/installs/nodejs/22.4.0/bin/node',
1 verbose cli   '/home/mestre/n8n/data/nodes/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'only-allow@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/home/mestre/.npm/_npx/1238703',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v22.4.0
4 verbose npm-session e37d003b7a3ffaa5
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/only-allow 31ms (from cache)
8 silly pacote tag manifest for only-allow@latest fetched in 65ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /home/mestre/n8n/data/nodes/node_modules/npx/node_modules/npm/node_modules/graceful-fs/poly>
9 verbose stack     at FSReqCallback.oncomplete (node:fs:199:5)
10 verbose cwd /home/mestre/n8n/data/nodes/node_modules/n8n-nodes-deepgram
11 verbose Linux 5.10.0-34-cloud-amd64
12 verbose argv "/home/mestre/.asdf/installs/nodejs/22.4.0/bin/node" "/home/mestre/n8n/data/nodes/node_modules/npx>
13 verbose node v22.4.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]

**Comment by Walid-Azur** [comment]
Let me check, it's working fine on my server, will retry a deploy. A quick gpt O3 investigation shows:
The error likely stems from mismatched Node and npm versions. Node 22 (latest) probably isn’t supported by n8n, which tends to work with Node 18 in its 1.x versions. Additionally, npm 5.1 (bundled with an older npx) may be causing compatibility issues. A potential fix is to use npm 10.x globally, upgrade npx, or revert to Node 18. Another approach could be to use n8n’s UI for installing custom packages. I might need to confirm or check Deepgram’s requirements for compatibility.

**Comment by gab-luz** [comment]
You're fast, sir. I've tried on both sides. On the n8n's UI and on the terminal. None seems to have worked. So far, I got about 30 community nodes, so I'm almost sure my install is ok.

**Comment by Walid-Azur** [comment]
I redployed the node again, and it works fine on docker version 1.9x

<img width="980" alt="Image" src="https://github.com/user-attachments/assets/6f8327d0-6af2-46a4-994e-b667b74e7383" />
<img width="720" alt="Image" src="https://github.com/user-attachments/assets/1d5f1e4c-8a36-495c-ab82-26b5422cd8e3" />

**Comment by gab-luz** [comment]
Ok. I'll try right now.

**Comment by gab-luz** [comment]
I'll have to close this issue for now, because 1.9.x is still in beta stage, it might be unstable.  I didn't work on 1.89.2, the latest stable version which I just updated to. Thanks for your hard work anyway. I guess 1.9.x will be up in a few days if I'm not mistaken.

**Comment by Walid-Azur** [comment]
requirement:

"engines": {
    "node": ">=18.10",
    "pnpm": ">=9.1"
  },
and "preinstall": "npx only-allow pnpm",
in module package
